defmodule Dg.Repo.Migrations.CreateUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :citext, null: false
      add :auth0_id, :text, null: false
      add :email_verified, :boolean
      add :picture, :text
      add :name, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:users, [:auth0_id], name: "users_unique_auth0_id_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists unique_index(:users, [:auth0_id], name: "users_unique_auth0_id_index")

    drop table(:users)
  end
end